* Gods and Devils
** Sol - Birth
Sol is known as the queen of kings and 'The Godess' or simply 'The Light'.  She is the only god worshipped by [[The Church][The Church]].  Her followers provide  healing and care for the sick, performs all rites and religeous rituals.  She prescribes kindness, forgiveness and family.
- Knowledge Check
  - 5  [[The Church][The Church]] is Technically /The Church of Sol/
  - 7  Sol is the godess of hope, joy and all things Beautiful
  - 10 The symbol of Sol is the verticle block 
  - 12 Sol didn't herself write [[The Prayers][The Prayers]]
  - 14 Priests and Priestesses of Sol aren't technically supposed to drink wine, smoke tabbacco, handle coin after the age of 26
  - 16 Sol is the wife of the mad god Mir
  - 18 Churches that can acomadate hungry or homeless, must do so
  - 20 [[The Church][The Church]] is actually very corrupt, especially at the top
  - 22 The verticle block encapsulated in a circle is actually a symbolic marriage between Sol and [[Mir - Life][Mir]]
** Mir - Life
Mir is the mad god of life.  Worshipped by forest dwellers and druids.  Celebration, Emotion, Poetry and Art, Plants and Animals are all in the Domain of Mir
- Knowledge Check
  - 5  Mir stories are for children
  - 7  Mir is worshipped by Witches and Druids
  - 10 The symbol of Mir is a circlet
  - 12 Worshippers of Mir don't have a holy book but instead have their prayers inscribed on stone and iron-wood
  - 14 Mir taught man about fire and cooking, crops and seed, carpentry and stonework, and befriended animals for man
  - 16 Mir has two wives, Sol and her sister
  - 18 Mir lost his mind and man found it
  - 20 Worshippers of Mir can speak the language of all animals
  - 22 Every winter solstice, a huge ritual is performed in a temple at the heart of the [[Grand Forest][Grand Forest]] to remind Mir to change the seasons, then again on the summer solstice to thank him
** Kad - Death
Kad is the god of death, the underworld and all things evil.  She is totally unknown by  most in the [[The Kingdom][Kingdom]] and to many who *do* know, thought to be a myth.
- Knowledge Check
  - 5  Kad is a curse word
  - 7  Witches and Warlocks worship a third, secret devil, Kad, who rules over hell
  - 10 Kad is the sister of Sol
  - 12 The Church destroys any record of Kad when they find it in creation
  - 14 Followers of Kad bear a mark somewhere on their body
  - 15 The funeral rites performed by the Church are actually based on an old Kad ritual
  - 16 Kad is also married to Mir
  - 18 The symbol of Kad is the horizontal bar
  - 20 Kad takes the form of a darkly fascinating witch harlot 
  - 22 Real and regular worship of Kad prevents natural death
* Lands and Seas
** Grand Forest
The Grand Forest, often called Mirwood, is the largest, oldest and most dense forest in the kingdom.  It is home to creatures magical and mundane.
** The Kingdom
Everything on the map is under the rule of the King or Queen
** Druuthenholm Mountains
The historical homelands of the Dwarves
** Lutra
The lands that makeup [[Lord Lutra][Lord Lutra]]'s region are known as /The Highlands/ or simply /Lutra/.  It is reasonably farmable and large.  The lands are known to produce more wheat then all other regions combined.  It is also famous for it's horses, cows, pigs and even chickens that seem to be extra alert, trainable and intellegent. 
* Cities and Towns
** Chendrin Hall
** Castle Heron
The *3rd* largest city in the [[The Kingdom][The Kingdom]], ruled over by the most powerful noble house other than the royal family themselves; [[House Heron][House Heron]].
** Burn Shire
Formerly a Beautiful farming community looked after by a noble lord.  When the lord's daughter was selected by [[Raz-Modian][Raz-Modian]], he decided to gather his knights and try to slay the dragon instead of paying tribute.  After Raz-Modian killed him and his men, he burned the village to cinders and it never fully recovered.  It is now called burn shire and is known for it's very *spicy dried green peppers*.
- Spicy Dried Green Peppers
  - 5gp
  - Consuming a few will ignite a day of hot sweat and fever after which the victim will be cured of any common sicknesses and infections.
** Blackstone
Blackstone is the capital of the kingdom, it is the largest city and boasts the oldest history and most attractions.  It is odly named, as no part of the city is made from anything that could be considered black stone.
- The Royal Castle
- <<Jingwei Basilica>>
  - Jingwei Basilica is a massive and Beautiful church of [[Sol - Birth][Sol]].  It has over a hundred chambers, no including [[The Catacombs][Catacombs]] that are on the rear grounds.
  - <<The Catacombs>> are a labryth of tombs and graves 
** Bondwafer
   Bondwafer is the largest and only Halfling town in [[The Kingdom][The Kingdom]].  It has a population of some odd 10,000 hobbits dispersed over a large region.  Most halflings live amoungst the other races and it is often said that there are more halflings in [[Blackstone][Blackstone]] than are in Bondwafer.
- <<Goodly Grue>> is an old and crazy *Gnome* who lives in a large patch of woods near Bondwafer.  He is one of the only creatures who believes himself to be a gnome.  He also has no real idea where the other gnomes live.  He is a tinkerer, inventer and alchemist who is currently most interested in [[Gold Creep][The yellow mold]] that grows near his cottage and in various other places.  He is an excellent gardener and potion brewer.
* Lords and Ladies
** Royal Family
The current royal family is [[The Laplass Family][The Laplass Family]].
** The Queen
The queen is considered by most to be cold and condescending.  Taking little interest in her individual citizens and focusing more on the power plays of the elite.  She is known for prefering simple but often radical solutions to petty problems like starvation and conflicts of inheritance.  In recent memory of the peasentry; she sent a legion of the guard to the farmlands of 
** Count Putnam Laplass
** Princess Eubuli
** High Priest Anslem
** Lady Jarvesetee
The last and only heir to the Jarvesetee house.  Jarvesetee lands are considered to be the finest in the land, with a utilitarian and productive people.  A famous phrase from all over the kingdom is a "Jarvesetee Begger" which means, a person who is sad about something small even though their life is generally alright.
** Lord Lutra
Sometimes called the "Wood King" or "Lord Butter-Bread", Lord Lutra looks after the largest singular swath of land inside [[The Kingdom][The Kingdom]].  His lands are famous for farming and animal husbandry.  His people are not rich or fashonable but are generally content.  Lord Lutra himself is a massave fat man who delights in little pleasures, jokes and theater.
* Factions and Guilds
** The Church
The only sanctioned religeon in [[The Kingdom][The Kingdom]].  Every city, town and even most hamlets have at least a shrine dedicated to [[Sol - Birth][Sol]] and under the direct control and curation of *The Church*.  The church welcomes all to it's services but within it's own ranchs, has a rigid structure and heirarchy.  Towns that are graced with a presence of the church have at least a priest, priestess or friar.  Some cities might have hundreds of clergy.  *The Church* doesn't directly involve itself in the day to day political functions of [[The Kingdom][The Kingdom]] but does have a single vote when it comes time to [[Royal Family][choose a royal house]].  Wise noble houses would do well to stay in the good graces of the church, since they command huge amounts of public and private opinion.
The church also provides communities with vital medical and disaster relief services.  They generally preach peace and forgiveness but when they [[Witchcraft][have reason]] they have little trouble finding a passage or two in [[The Prayers][The Prayers]] to excuse violent torture.
The Church is organized in the following way
- First Archon
  - Archon
    - Imam
      - Awakened Dreamer
	- Enlightened Dreamer
	  - Adept
	    - Initiate
	      - Neophite
      - Flagulant
	- Initiate
	  - Neophite
** The Draco-Cults
There is only one Draco-Cult that moves through the kingdom in broad daylight, that is the cult of [[Raz-Modian][Raz-Modian]].  Every year, the agents of the red dragon select a maiden from amoungst the citizenry and bring her back to Raz-Modian.  This is done with full knowledge and protection of the King.  Many see it as a neccesarry evil and do their best not to draw the attention of any Draco-Cultists. Unknown to most, there are members of other Draco-Cults, in service to some of the other dragons.
** House Heron
 One of the most powerful and largest noble houses in [[The Kingdom][The Kingdom]].  Known for their riches, the size of their territory and the size of their family.  The house boasts over a hundred lords and ladies.
** The Magi
The magi is a catch all term for the arcane casters of the kingdom.  Magi aren't a unified group even though they are often considered so by the peoples of [[The Kingdom][The Kingdom]].  Many Magi take on apprentices or sit on councils but there isn't a singlular rule or convention regarding their ways.
** The Laplass Family
The Laplass family has been in control of the throne for almost a century.  Members of the Laplass family are simultaneously known for long life and violent death.  The eldest living memeber is [[Count Putnam Laplass][Count Putnam Laplass]] but [[The Queen][The Queen]] herself is said to be not much younger.
** The Justice
The Justice is the name for the royal knights granted total freedom to protect the kingdom and carry out the wishes of the [[Royal Family][Royal Family]].  Although they are all knighted, many of them do not wear gleaming armor and ride horses, they are often drab and debonair.
* Myth and Minutiae
** Witchcraft
Magic of the wizarding sort is rare within [[The Kingdom][The Kingdom]].  It is most often found within the halls of on of the [[The Magi][Magi schools of magic]].  Most common folk find /polite/ tricks of magic amusing and harmless but tend do decide for themselves what is friendly magic and what is witchcraft.  [[The Church][The Church]] has no problem amplifiying such suspicians of the dark arts.
** Raz-Modian
The great old collosal red dragon that dominates the north eastern [[Druuthenholm Mountains][Druuthenholm Mountains]]
** The Prayers
The holy book that is kept by all true followers of [[Sol - Birth][Sol]].  Copies are created, blessed and sold by [[The Church][The Church]] and updated periodically by a process called [[Illumination][Illumination]].  It is forbidden by law in [[The Kingdom][The Kingdom]] to possess an un-illuminated copy of The Prayers and they are destroyed whenever found.
** Illumination
A perfect original of [[The Prayers][The Prayers]] is kept in the [[Jingwei Basilica][Jingwei Basilica]]  Anything written into the original book there, is magically transfered into all illuminated copies of the prayers.
** Gold Creep
Gold creep is a wheat-yellow fungus or lichon that spreads liberally in some parts of [[The Kingdom][The Kingdom]] usuaully in forests but there is a famous patch just outside [[Bondwafer][Bondwafer]].  It isn't clear what Gold Creep is but it is somewhat edible and sweet, can be scraped into a powder and some say it has healing powers--Most consider it a blight on the land because of how it covers everything and can choke out plants and passerbys alike.  All polen eating animnals seem attracted to it and weeds flourish from under it.  [[Goodly Grue][Goodly Grue]], is the formost expert on Gold Creep.
